// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2019-05-21 22:12:36.013123 -0500 CDT m=+0.003802461
package framework

import (
	"github.com/kgrunwald/goweb/controller"
	"github.com/kgrunwald/goweb/di"
	"github.com/kgrunwald/goweb/ilog"
	"github.com/kgrunwald/goweb/router"
)

func BuildContainer() di.Container {
	c := di.NewContainer()
	c.RegisterGroup(controller.NewT, di.GroupController)
	c.Register(ilog.NewLogger)
	c.Register(router.NewRouter)
	c.Register(router.Initialize)
	return c
}
